apiVersion: v1
kind: Service
metadata:
  name: ai-research-backend-service
  namespace: ai-research-agent
  labels:
    app: ai-research-backend
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30800
    protocol: TCP
    name: http
  selector:
    app: ai-research-backend