apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-research-config
  namespace: ai-research-agent
data:
  AWS_REGION: "us-east-1"
  PUBLIC_IP: "localhost"
---
apiVersion: v1
kind: Secret
metadata:
  name: ai-research-secrets
  namespace: ai-research-agent
type: Opaque
stringData:
  SERP_API_KEY: "your_serp_api_key_here"
  NEWSDATA_API_KEY: "your_newsdata_api_key_here"
  TAVILY_API_KEY: "your_tavily_api_key_here"
  AWS_ACCESS_KEY_ID: "your_aws_access_key_here"
  AWS_SECRET_ACCESS_KEY: "your_aws_secret_key_here"
  GOOGLE_API_KEY: "your_google_api_key_here"
  GOOGLE_CSE_ID: "your_google_cse_id_here"