apiVersion: v1
kind: Service
metadata:
  name: ai-research-frontend-service
  namespace: ai-research-agent
  labels:
    app: ai-research-frontend
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30300
    protocol: TCP
    name: http
  selector:
    app: ai-research-frontend